### ISSUE TITLE
README file for gke module is too vague about required permissions

### ISSUE THREAD

**Issue by svenchilton** [NVIDIA/nvidia-terraform-modules#6]
Point 3 in the Prerequisites > Setup section of https://github.com/NVIDIA/nvidia-terraform-modules/blob/main/gke/README.md reads: 

> To run this module assumes elevated permissions in your GCP account, specifically permissions to create VPC networks, GKE clusters, and Compute nodes. This will not work on accounts using the "free plan" as you cannot use GPU nodes until a billing account is attached and activated.

I found in validating this workflow that Kubernetes Engine Admin permissions were required. I suggest changing the wording to something like 

> To run this module assumes Kubernetes Engine Admin permissions in your GCP account. This will not work on accounts using the "free plan" as you cannot use GPU nodes until a billing account is attached and activated.

**Comment by MaggieXJZhang** [comment]
Thanks for the rewording, fixed the readme, closing issue.
